#!/bin/sh

# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <https://unlicense.org>

if [ -n "$1" ]; then
    if [ -z "$(aws configure get profile.$1.sso_start_url)" ]; then
        aws configure set profile.$1.sso_start_url $AWS_CONFIGURE_SSO_DEFAULT_START_URL
    fi;
    if [ -z "$(aws configure get profile.$1.sso_region)" ]; then
        aws configure set profile.$1.sso_region $AWS_CONFIGURE_SSO_DEFAULT_REGION
    fi;
    aws configure sso --profile $1
else
    echo Usage: $(basename $0) PROFILE
    echo Set default sso_start_url with AWS_CONFIGURE_SSO_DEFAULT_START_URL
    echo Set default sso_region    with AWS_CONFIGURE_SSO_DEFAULT_REGION
fi;
