# Copyright 2022 Ben Kehoe
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  NumChildStacks:
    Type: Number
    Default: -1
  MaxAssignmentsAllocation:
    Type: Number
    Default: -1
  LookupNames:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  DefaultSessionDuration:
    Type: String
    Default: ""
  ChildTemplatesInYaml:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  MaxConcurrentAssignments:
    Type: Number
    Default: -1
  MaxResourcesPerTemplate:
    Type: Number
    Default: -1
  LogLevel:
    Type: String
    Default: INFO
  ArtifactS3KeyPrefix:
    Type: String
    Default: ""
  S3PutObjectArgs:
    Type: String
    Default: ""
Outputs:
  MacroName:
    Value: !Ref Macro
  MacroFunctionName:
    Value: !Ref MacroFunction
  MacroFunctionArn:
    Value: !GetAtt MacroFunction.Arn
    Export:
      Name: SSOUtilMacroFunctionArn
  MacroArtifactBucketName:
    Value: !Ref MacroArtifactBucket
  MacroArtifactBucketArn:
    Value: !GetAtt MacroArtifactBucket.Arn
  MacroAccessPolicy:
    Value: !Ref MacroAccessPolicyResource
    Export:
      Name: SSOUtilMacroAccessPolicy
Resources:
  MacroAccessPolicyResource:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SSOUtilMacroAccess
      Description: Allow invoke on the macro Lambda function and GetObject on the artifact bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource: !GetAtt MacroFunction.Arn
        - Effect: Allow
          Action: s3:GetObject
          Resource: !Sub "${MacroArtifactBucket.Arn}/*"

  MacroArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: True
        BlockPublicAcls: True

  MacroArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MacroArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AllowCloudFormation
          Effect: Allow
          Principal: {"Service": "cloudformation.amazonaws.com"}
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::${MacroArtifactBucket}/*"

  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 900
      CodeUri: ../cli/src
      Handler: cfn_macro_handler.handler
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          BUCKET_NAME: !Ref MacroArtifactBucket
          KEY_PREFIX: !Ref ArtifactS3KeyPrefix
          S3_PUT_OBJECT_ARGS: !Ref S3PutObjectArgs
          LOOKUP_NAMES: !Ref LookupNames
          MAX_RESOURCES_PER_TEMPLATE: !Ref MaxResourcesPerTemplate
          MAX_CONCURRENT_ASSIGNMENTS: !Ref MaxConcurrentAssignments
          MAX_ASSIGNMENTS_ALLOCATION: !Ref MaxAssignmentsAllocation
          NUM_CHILD_STACKS: !Ref NumChildStacks
          DEFAULT_SESSION_DURATION: !Ref DefaultSessionDuration
          CHILD_TEMPLATES_IN_YAML: !Ref ChildTemplatesInYaml
      Policies:
        Version: "2012-10-17"
        Statement:
        - Sid: CloudFormation
          Effect: Allow
          Action: s3:PutObject
          Resource: !Sub "arn:aws:s3:::${MacroArtifactBucket}/*"
        - Sid: AWSSSO
          Effect: Allow
          Action:
          - sso:ListInstances
          - sso:DescribePermissionSet
          Resource: "*"
        - Sid: Organizations
          Effect: Allow
          Action:
          - organizations:ListAccountsForParent
          - organizations:ListOrganizationalUnitsForParent
          - organizations:DescribeAccount
          - organizations:DescribeOrganization
          - organizations:DescribeOrganizationalUnit
          Resource: "*"
        - Sid: IdentityStore
          Effect: Allow
          Action:
          - identitystore:DescribeUser
          - identitystore:DescribeGroup
          Resource: "*"

  MacroLogsRoleForCfn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal: {"Service": "cloudformation.amazonaws.com"}
          Action: sts:AssumeRole
      Policies:
        - PolicyName: LogWriting
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Effect: Allow
              Action: "logs:*"
              Resource: "*"

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: AWS-SSO-Util-2020-11-08
      Description: Handlers for AWS SSO
      FunctionName: !Ref MacroFunction
      LogGroupName: /sso-util/macro
      LogRoleARN: !GetAtt MacroLogsRoleForCfn.Arn
